site_name: Rookedsysc's Docs

theme: 
  name: material
  language: kr
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.top
    # - navigation.expand
    - content.code.annotate
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 4
  - attr_list
  - md_in_html


plugins:
  - search

# Git 연동
site_name: Rookedsysc's Docs
site_url: https://lokigem.github.io/docs
repo_url: https://github.com/rookedsysc
repo_name: rookedsysc
    
nav: 
  - Flutter:
    - Dart Grammar:
      - Flutter/dartGrammar/DartGrammar.md
      - Flutter/dartGrammar/oopProgramming.md
      - Flutter/dartGrammar/functionalProgramming.md
      - Flutter/dartGrammar/asyncProgramming.md
      - Flutter/dartGrammar/Date.md
      - Flutter/dartGrammar/formatting.md
    - Flutter Theory:
      - Flutter/Theory/widget.md
      - Flutter/Theory/SQL.md
      - Flutter/Theory/CodeGeneration.md
      - Flutter/Theory/text_form_field.md
      - Flutter/Theory/Navigation.md
      - Flutter/Theory/notification.md
      - Design:
        - Flutter/Theory/design/row_and_column.md
        - Flutter/Theory/design/Button.md
        - Flutter/Theory/design/Builder.md
        - Flutter/Theory/design/GestureDetector.md
        - Scrollable_widget: 
          - Flutter/Theory/design/scrollable_widget/index.md   
          - Flutter/Theory/design/scrollable_widget/scrollListner.md
        - Flutter/Theory/design/animatedOpacity.md   
        - Flutter/Theory/design/drawer.md
        - Flutter/Theory/design/size.md

    - Flutter Packages:
      - Flutter/Packages/web_view.md
      - Flutter/Packages/drift.md
      - Flutter/Packages/Hive.md

  
