
theme: 
  name: material
  language: kr
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.top
    # - navigation.expand
    - content.code.annotate
    - content.tabs.link

  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 4
  - attr_list
  - md_in_html


plugins:
  - search

# Git 연동
site_name: Rookedsysc's Docs
site_url: https://lokigem.github.io/docs
repo_url: https://github.com/rookedsysc
repo_name: rookedsysc
    
nav: 
  - Flutter:
    - Dart Grammar:
      - Flutter/dartGrammar/DartGrammar.md
      - Flutter/dartGrammar/oopProgramming.md
      - Flutter/dartGrammar/functionalProgramming.md
      - Flutter/dartGrammar/asyncProgramming.md
      - Flutter/dartGrammar/Date.md
      - Flutter/dartGrammar/formatting.md
    - Flutter Theory:
      - Flutter/Theory/widget.md
      - Flutter/Theory/SQL.md
      - Flutter/Theory/CodeGeneration.md
      - Flutter/Theory/text_form_field.md
      - Flutter/Theory/dropdown_button.md
      - Flutter/Theory/Navigation.md
      - Flutter/Theory/notification.md
      - Flutter/Theory/error_fix.md
    - Flutter Packages:
      - Flutter/Packages/riverpod.md
      - Flutter/Packages/Hive.md
      - Flutter/Packages/google_maps.md
      - Flutter/Packages/web_view.md
      - Flutter/Packages/easy_localization.md
      - Flutter/Packages/drift.md
    - Flutter Design:
      - Flutter/design/row_and_column.md
      - Flutter/design/Button.md
      - Flutter/design/Builder.md
      - Flutter/design/GestureDetector.md
      - Scrollable_widget: 
        - Flutter/design/scrollable_widget/index.md   
        - Flutter/design/scrollable_widget/scrollListner.md
      - Flutter/design/animatedOpacity.md   
      - Flutter/design/drawer.md
      - Flutter/design/modal_bottom_sheet.md
      - Flutter/design/size.md



