site_name: Rookedsysc's Docs

theme: 
  name: material
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - content.code.annotate
  palette:
    scheme: slate
    primary: blue
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 4
  - attr_list
  - md_in_html


plugins:
  - search

# Git 연동
site_name: Rookedsysc's Docs
site_url: https://lokigem.github.io/docs
repo_url: https://github.com/rookedsysc
repo_name: rookedsysc
    
nav: 
  - Flutter:
    - Dart Grammar:
      - Flutter/dartGrammar/DartGrammar.md
      - Flutter/dartGrammar/oopProgramming.md
      - Flutter/dartGrammar/functionalProgramming.md
      - Flutter/dartGrammar/asyncProgramming.md
      - Flutter/dartGrammar/Date.md
    - Flutter Theory:
      - Flutter/Theory/row_and_column.md
      - Flutter/Theory/widget.md
      - Flutter/Theory/Button.md
      - Flutter/Theory/Builder.md
      - Flutter/Theory/Navigation.md
      - Flutter/Theory/GestureDetector.md
      - Flutter/Theory/SQL.md

    - Flutter Packages:
      - Flutter/Packages/web_view.md

  
