site_name: Rookedsysc's Docs

theme: 
  name: material
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - content.code.annotate
    - navigation.top
    - navigation.sections

  palette:
    scheme: default
    primary: black
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 4
  - attr_list
  - md_in_html


plugins:
  - search

# Git 연동
site_name: Rookedsysc's Docs
site_url: https://lokigem.github.io/docs
repo_url: https://github.com/lokigem/docs
repo_name: lokigem/docs
    
nav: 
  - Flutter:
    - Dart Grammar:
      - Flutter/dartGrammar/DartGrammar.md
      - Flutter/dartGrammar/oopProgramming.md
      - Flutter/dartGrammar/functionalProgramming.md
      - Flutter/dartGrammar/asyncProgramming.md
    - Flutter Theory:
      - Flutter/flutterTheory/row_and_column.md
      - Flutter/flutterTheory/widget.md
    - Flutter Packages:
      - Flutter/flutterPackages/web_view.md

  - Computer Sience:
    - 디지털 공학개론:
      - ComputerSience/디지털_공학개론/디지털_논리회로와_컴퓨터.md
      - ComputerSience/디지털_공학개론/아날로그_신호_디지털신호_변환.md

